apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flask-configmap-prod.yaml
  - flask-deployment-prod.yaml
  - flask-ingress-prod.yaml
  - flask-nodeport-prod.yaml
  - flask-service-prod.yaml
  - mysql-configmap-prod.yaml
  - mysql-network-policy-prod.yaml
  - mysql-secret-prod.yaml
  - mysql-service-prod.yaml
  - mysql-statefulset-prod.yaml

images:
  - name: tarekadel/k8s-flask-mysql-flaskapp
    newTag: "v10"   # هنا هتحط الإصدار الجديد للـ flask-app
  - name: tarekadel/k8s-flask-mysql-database
    newTag: "v13"   # هنا هتحط الإصدار الجديد للـ mysql

patches:
  - target:
      kind: Deployment
      name: flask-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: StatefulSet
      name: mysql
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
