apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  root-password: cm9vdA==             # "root"
  mysql-user: Zmxhc2t1c2Vy            # "flaskuser"
  mysql-password: eW91cnBhc3N3b3Jk    # "yourpassword"
