apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
    - default:
        memory: 1Gi        # 1024Mi
        cpu: 500m
      defaultRequest:
        memory: 512Mi
        cpu: 300m
      type: Container

