apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.155     # ← IP بتاع NFS
    path: /mnt/nfs-share      # ← نفس المسار اللي عملته
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage

